### ISSUE TITLE
Parsing error for "autocmd insertleave * nested silent! write"

### ISSUE THREAD

**Issue by astier** [hrsh7th/vim-vsnip#162]
## Problem

Hi. I get a parsing error when I have an autocmd to autosave on insertleave and try to expand snippets in certain files. I use neovim-nightly.

## Error

```
[vsnip] Parsing error occurred on: /home/user/projects/dotfiles/nvim/snippets/json.json
{'throwpint': 'function <SNR>25_expand_or_jump[17]..30[1]..vsnip#get_context[9]..vsnip#source#find[2]..vsnip#so
urce#user_snippet#find[4]..vsnip#source#create, line 5', 'exception': 'Vim(let):E474: Trailing characters: f'}
```

## Minimal vimrc

```vim
set runtimepath+=~/.local/share/nvim/plugins/vim-vsnip
let g:vsnip_snippet_dir = '~/.config/nvim/snippets'
imap <silent> <expr> <tab> vsnip#available(1) ? '<plug>(vsnip-expand-or-jump)' : '<tab>'
autocmd insertleave * nested silent! write
```

## Reproduce

1. Create minimal vimrc
2. Create snippet-file `json.json` with following snippet:
```json
{
  "foo": {
    "prefix": ["f"],
    "body": [ "foo" ]
  }
}
```
3. Open the file json.json with vim
4. Enter insert mode, type `f`, press tab to expand snippet
5. Observe the error-message

**Comment by hrsh7th** [comment]
@astier It is caused by `autocmd insertleave * nested silent! write`.

In vsnip, the snippet expansion will cancel insert-mode. https://github.com/hrsh7th/vim-vsnip/blob/master/plugin/vsnip.vim#L80

So this problem was caused by 

1. Insert `f` (At this time, the `json.json` is not a valid json)
2. Expand `f` (At this time, vsnip cancel insert-mode so the `autocmd insertleave * nested silent! write` will raised)
3. The vsnip detects `source file changes` automatically (it detected as invalid json).

The vsnip will show error message if source json is invalid.

**Comment by hrsh7th** [comment]
I think we have nothing to do with this problem.
Could you explain what you want if you have different opinion?

**Comment by astier** [comment]
Ok. That makes sense. Actually I discovered it first because it happened in the global.json file. I guess not much can be done about it.

**Comment by hrsh7th** [comment]
Thank you for your response!
